
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-example-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: xinminlabs/kubernetes-rails-example:latest
        env:
        - name: EXAMPLE
          value: This env variable is defined by Kubernetes.
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: rails_master_key
        envFrom:
        - configMapRef:
            name: env
        ports:
        - containerPort: 3000
